name: trigger migration by pr comment

on:
  issue_comment:
    types: [created]

jobs:
  run-migration:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/migrate') }} # only comment in pr and contains '/migrate'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run migration
        run: pnpm migrate >> $GITHUB_OUTPUT
        id: migrate

      - name: add result comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.migrate.outcome == 'success'
        with:
          recreate: true
          message: |
            ### Migrate command output
            ${{ join(steps.migrate.outputs, '\n') }}

